 <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4" style="padding-top: 0 !important; margin-top: 0 !important;">
                    <h2 style="font-weight: 700;margin-top: 0; margin-bottom: 18px; padding: 10px 18px; border-radius: 8px 8px 0 0; text-align: left; letter-spacing: 1px;">Certificates Request</h2>
                    <div class="card mb-4">
                        <div style="height: 4px; background: #A9D8DE; border-radius: 8px 8px 0 0; margin-bottom: 0;"></div>
                        <div class="card-body">
                            <table id="datatablesSimple">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Request ID</th>
                                        <th>Child's Name</th>
                                        <th>Requested By</th>
                                        <th>Status</th>
                                        <th>Date Required</th>
                                        <th>Date Requested</th>
                                        <th>Date Approved</th>
                                        <th>Generated By</th>
                                        <th>Approved/Rejected By</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><i class="fa-solid fa-flag" style="color: #00b300;"></i></td>
                                        <td>REQ-001</td>
                                        <td>John Doe</td>
                                        <td>Mary Smith</td>
                                        <td>Pending</td>
                                        <td>2024-06-10</td>
                                        <td>2024-06-01</td>
                                        <td>2024-06-11</td>
                                        <td>Church Staff</td>
                                        <td>Church Staff</td>
                                        <td><button class="btn btn-success btn-sm approve-btn" data-request="REQ-001">Approve</button></td>
                                    </tr>
                                    <tr>
                                        <td><i class="fa-solid fa-flag" style="color: #00b300;"></i></td>
                                        <td>REQ-002</td>
                                        <td>Jane Smith</td>
                                        <td>Paul Brown</td>
                                        <td>Approved</td>
                                        <td>2024-06-12</td>
                                        <td>2024-06-02</td>
                                        <td>2024-06-03</td>
                                        <td>Church Staff</td>
                                        <td>Church Staff</td>
                                        <td><button class="btn btn-success btn-sm approve-btn" data-request="REQ-002">Approve</button></td>
                                    </tr>
                                    <tr>
                                        <td><i class="fa-solid fa-flag" style="color: #00b300;"></i></td>
                                        <td>REQ-003</td>
                                        <td>Michael Lee</td>
                                        <td>Sarah White</td>
                                        <td>Rejected</td>
                                        <td>2024-06-15</td>
                                        <td>2024-06-03</td>
                                        <td>2024-06-04</td>
                                        <td>Church Staff</td>
                                        <td>Church Staff</td>
                                        <td><button class="btn btn-success btn-sm approve-btn" data-request="REQ-003">Approve</button></td>
                                    </tr>
                                    <tr>
                                        <td><i class="fa-solid fa-flag" style="color: #00b300;"></i></td>
                                        <td>REQ-004</td>
                                        <td>Emily Clark</td>
                                        <td>David Green</td>
                                        <td>Pending</td>
                                        <td>2024-06-18</td>
                                        <td>2024-06-04</td>
                                        <td>2024-06-04</td>
                                        <td>Church Staff</td>
                                        <td>Church Staff</td>
                                        <td><button class="btn btn-success btn-sm approve-btn" data-request="REQ-004">Approve</button></td>
                                    </tr>
                                    <tr>
                                        <td><i class="fa-solid fa-flag" style="color: #00b300;"></i></td>
                                        <td>REQ-005</td>
                                        <td>Olivia Brown</td>
                                        <td>James Black</td>
                                        <td>Pending</td>
                                        <td>2024-06-20</td>
                                        <td>2024-06-05</td>
                                        <td>2024-06-04</td>
                                        <td>Church Staff</td>
                                        <td>Church Staff</td>
                                        <td><button class="btn btn-success btn-sm approve-btn" data-request="REQ-005">Approve</button></td>
                                    </tr>
                                    <tr>
                                        <td><i class="fa-solid fa-flag" style="color: #00b300;"></i></td>
                                        <td>REQ-006</td>
                                        <td>Lucas White</td>
                                        <td>Emma Blue</td>
                                        <td>Pending</td>
                                        <td>2024-06-22</td>
                                        <td>2024-06-06</td>
                                        <td>2024-06-04</td>
                                        <td>Church Staff</td>
                                        <td>Church Staff</td>
                                        <td><button class="btn btn-success btn-sm approve-btn" data-request="REQ-006">Approve</button></td>
                                    </tr>
                                    <tr>
                                        <td><i class="fa-solid fa-flag" style="color: #00b300;"></i></td>
                                        <td>REQ-007</td>
                                        <td>Sophia King</td>
                                        <td>Chris Red</td>
                                        <td>Pending</td>
                                        <td>2024-06-25</td>
                                        <td>2024-06-07</td>
                                        <td>2024-06-04</td>
                                        <td>Church Staff</td>
                                        <td>Church Staff</td>
                                        <td><button class="btn btn-success btn-sm approve-btn" data-request="REQ-007">Approve</button></td>
                                    </tr>
                                    <tr>
                                        <td><i class="fa-solid fa-flag" style="color: #00b300;"></i></td>
                                        <td>REQ-008</td>
                                        <td>William Black</td>
                                        <td>Linda Pink</td>
                                        <td>Pending</td>
                                        <td>2024-06-28</td>
                                        <td>2024-06-08</td>
                                        <td>2024-06-04</td>
                                        <td>Church Staff</td>
                                        <td>Church Staff</td>
                                        <td><button class="btn btn-success btn-sm approve-btn" data-request="REQ-008">Approve</button></td>
                                    </tr>
                                    <tr>
                                        <td><i class="fa-solid fa-flag" style="color: #00b300;"></i></td>
                                        <td>REQ-009</td>
                                        <td>Charlotte Grey</td>
                                        <td>Brian Orange</td>
                                        <td>Pending</td>
                                        <td>2024-06-30</td>
                                        <td>2024-06-09</td>
                                        <td>2024-06-04</td>
                                        <td>Church Staff</td>
                                        <td>Church Staff</td>
                                        <td><button class="btn btn-success btn-sm approve-btn" data-request="REQ-009">Approve</button></td>
                                    </tr>
                                    <tr>
                                        <td><i class="fa-solid fa-flag" style="color: #00b300;"></i></td>
                                        <td>REQ-010</td>
                                        <td>Amelia Violet</td>
                                        <td>George Yellow</td>
                                        <td>Pending</td>
                                        <td>2024-07-02</td>
                                        <td>2024-06-10</td>
                                        <td>2024-06-04</td>
                                        <td>Church Staff</td>
                                        <td>Church Staff</td>
                                        <td><button class="btn btn-success btn-sm approve-btn" data-request="REQ-010">Approve</button></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </main>